name: wgc.base.services
version: '3.8'

services:
  shema.fitnessapp:
    image: ghcr.io/andrejhristovski/Fitness-Tracker:${BASE_SERVICE_IMAGE_TAG:-latest}
    container_name: shema.fitnessapp
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped
    networks:
      - shema.public

networks:
  shema.public:
    external: true
    name: ${SHARED_NETWORK_NAME}